import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { cookies } from "next/headers";

import { Navbar } from "./components/navbar";
import { TRPCReactProvider } from "~/trpc/react";
import { Toaster } from "~/app/components/ui/sonner";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`px-4 font-sans sm:px-10 ${inter.variable}`}>
        <TRPCReactProvider cookies={cookies().toString()}>
          <Toaster />
          <Navbar />
          {children}
        </TRPCReactProvider>
      </body>
    </html>
  );
}
